# Generated by Django 2.1 on 2020-04-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handclean_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jingle', models.CharField(max_length=255)),
                ('myreview', models.TextField(blank=True, max_length=1000)),
                ('picture', models.ImageField(blank=True, upload_to='posters_review')),
            ],
        ),
    ]
