# Generated by Django 2.1 on 2020-04-15 18:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('handclean_app', '0003_auto_20200415_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2020, 4, 15, 18, 7, 55, 614099, tzinfo=utc)),
        ),
    ]
