# Generated by Django 2.1 on 2020-04-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handclean_app', '0006_auto_20200430_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='picture',
            field=models.ImageField(upload_to='posters_review'),
        ),
    ]
