# Generated by Django 2.1 on 2020-04-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handclean_app', '0007_auto_20200430_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='char_pic',
            field=models.CharField(default='https://res.cloudinary.com/do8xzkgcs/image/upload/v1571618470/gbvmr9fwrwcz9xp0ycos.png', max_length=1000),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='picture',
            field=models.ImageField(blank=True, upload_to='posters_review'),
        ),
    ]
